//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int DeptCourseID { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public int PresentDays { get; set; }
        public int AbsentDays { get; set; }
        public int OffDays { get; set; }
        public int Leave { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual DeptCourse DeptCourse { get; set; }
    }
}
