//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeptCourse()
        {
            this.Groups = new HashSet<Group>();
            this.ManageTimeTables = new HashSet<ManageTimeTable>();
        }
    
        public int ID { get; set; }
        public int DepartmentID { get; set; }
        public int CourseID { get; set; }
        public int SemesterNo { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual Course Course { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManageTimeTable> ManageTimeTables { get; set; }
        public virtual TimeTable TimeTable { get; set; }
    }
}
