//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalRank
    {
        public int ID { get; set; }
        public int StaffID { get; set; }
        public string RankName { get; set; }
        public System.DateTime RankDate { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
