//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalBackground
    {
        public int ID { get; set; }
        public int StaffID { get; set; }
        public string Degree { get; set; }
        public string CampusName { get; set; }
        public string CampusLocation { get; set; }
        public System.DateTime GraduationDate { get; set; }
        public byte[] Attachment { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
