//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health
    {
        public int ID { get; set; }
        public string BloodGroup { get; set; }
        public byte[] HIV { get; set; }
        public byte[] HepatitisB { get; set; }
        public byte[] EyeDisease { get; set; }
        public byte[] SkinDisease { get; set; }
        public byte[] ENT { get; set; }
        public byte[] SurgeryDisease { get; set; }
        public byte[] TB { get; set; }
        public byte[] InternalDisease { get; set; }
        public byte[] NeurologicMentalDisease { get; set; }
        public byte[] Attachment { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
