//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HostelRegistration()
        {
            this.Clearances = new HashSet<Clearance>();
        }
    
        public int ID { get; set; }
        public int HostelID { get; set; }
        public int StudentID { get; set; }
        public int RegistrationDate { get; set; }
        public int RoomID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clearance> Clearances { get; set; }
        public virtual Hostel Hostel { get; set; }
        public virtual HostelAttendance HostelAttendance { get; set; }
        public virtual Student Student { get; set; }
    }
}
