//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelAttendance
    {
        public int ID { get; set; }
        public int HostelID { get; set; }
        public int RegistrationID { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public int TotalDays { get; set; }
        public int PresentDays { get; set; }
        public int AbsentDays { get; set; }
        public int OffDays { get; set; }
        public int Leave { get; set; }
    
        public virtual Hostel Hostel { get; set; }
        public virtual HostelRegistration HostelRegistration { get; set; }
    }
}
