//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KIHSEntities : DbContext
    {
        public KIHSEntities()
            : base("name=KIHSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Clearance> Clearances { get; set; }
        public virtual DbSet<Coordinator> Coordinators { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DeptCourse> DeptCourses { get; set; }
        public virtual DbSet<EducationalBackground> EducationalBackgrounds { get; set; }
        public virtual DbSet<EducationalRank> EducationalRanks { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<ExamTimeTable> ExamTimeTables { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Hostel> Hostels { get; set; }
        public virtual DbSet<HostelAttendance> HostelAttendances { get; set; }
        public virtual DbSet<HostelRegistration> HostelRegistrations { get; set; }
        public virtual DbSet<ManageTimeTable> ManageTimeTables { get; set; }
        public virtual DbSet<NightShift> NightShifts { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<ShowTimeTable> ShowTimeTables { get; set; }
        public virtual DbSet<TimeTable> TimeTables { get; set; }
        public virtual DbSet<Tool> Tools { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Health> Healths { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<SchoolBackground> SchoolBackgrounds { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<ScoreDetail> ScoreDetails { get; set; }
    }
}
