//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime HireDate { get; set; }
        public string Office { get; set; }
        public string OfficeEmail { get; set; }
        public string OfficeCellNumber { get; set; }
        public string Position { get; set; }
        public string Province { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
