//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreDetail
    {
        public int ID { get; set; }
        public int ScoreID { get; set; }
        public int ScoreType { get; set; }
        public int ScorePercentage { get; set; }
        public int ExamMarks { get; set; }
    
        public virtual Score Score { get; set; }
    }
}
