//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Score()
        {
            this.ScoreDetails = new HashSet<ScoreDetail>();
        }
    
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int TimeTableID { get; set; }
        public string EducationalYear { get; set; }
        public string Semester { get; set; }
        public System.DateTime ExamDate { get; set; }
        public string Chance { get; set; }
    
        public virtual ExamTimeTable ExamTimeTable { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreDetail> ScoreDetails { get; set; }
    }
}
