//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.EducationalBackgrounds = new HashSet<EducationalBackground>();
            this.EducationalRanks = new HashSet<EducationalRank>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string LastName { get; set; }
        public string ActiveDegree { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string POB { get; set; }
        public string NativeLanguage { get; set; }
        public string Nationality { get; set; }
        public int NID { get; set; }
        public string CellPhone { get; set; }
        public System.DateTime HireDate { get; set; }
        public byte[] Photo { get; set; }
        public byte[] Maktoob { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationalBackground> EducationalBackgrounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationalRank> EducationalRanks { get; set; }
        public virtual Address Address { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
