//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int ID { get; set; }
        public int DeptCourseID { get; set; }
        public int TeacherID { get; set; }
        public string PresentDay { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual DeptCourse DeptCourse { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
